# Generated by Django 6.0.4 on 2026-04-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirwafab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
