# Generated by Django 6.0.1 on 2026-04-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirwafab', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_own_profile', 'Can view own profile'), ('change_own_profile', 'Can edit own profile'), ('change_own_password', 'Can change own password'), ('view_user_directory', 'Can view user directory'), ('view_all_profiles', 'Can view all profiles'), ('view_user_activity', 'Can view user activity'), ('download_reports', 'Can download reports')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
