# Generated by Django 6.0.4 on 2026-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirwafab', '0006_fix_group_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hirwafab_login_attempt',
                'indexes': [models.Index(fields=['username', 'timestamp'], name='hirwafab_lo_usernam_0013bf_idx'), models.Index(fields=['ip_address', 'timestamp'], name='hirwafab_lo_ip_addr_fd578e_idx')],
            },
        ),
    ]
